### ISSUE TITLE
prima opäť nefunkčná?

### ISSUE THREAD

**Issue by michalhainc** [Limoto/tv-dl#16]
ahoj, vcera som pustil tvoj kod v debuggeri a opat po otvoreni rtmp streamu rtmpdump hlasi ze server zatvoril spojenie... tak asi nieco zase zmenili...  any ideas? :)

btw keep up good work ;)

**Comment by Limoto** [comment]
Napiš, co konkrétně ti nejde stáhnout a hoď sem aspoň debug výstup. Mně to funguje.

**Comment by michalhainc** [comment]
caf, no tak tu to je

url stranky je http://play.iprima.cz/iprima/173387/2290

do metody download v tv-dl.py pride parameter d takto:

tuple: ('rtmp', '807403_BC_HQ_12850.flv.flv', {'url': 'rtmp://bcastlw.livebox.cz:80/iprima_token?
 auth=_any_|1364985608|44a3bcd6ea02c7e7ea1d8e647ace1b54a9915489/807403_BC_HQ_12850.flv.mp4', 
 'rtmpdump_args': '--live'})

rtmpdump sa potom spusti nasledovne:

rtmpdump.exe -r "rtmp://bcastlw.livebox.cz:80/iprima_token?
 auth=_any_|1364985608|44a3bcd6ea02c7e7ea1d8e647ace1b54a9915489/807403_BC_HQ_12850.flv.mp4" -o 
 "807403_BC_HQ_12850.flv.flv"  --live

no a vystup z rtmpdump je 

RTMPDump v2.3
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.StreamNotFound

nacrta sa mi tu otazka aku verziu rtmpdump pouzivas?

**Comment by Limoto** [comment]
Tak tohle mi taky nešlo, teď už by to jít mělo.

**Comment by michalhainc** [comment]
Diky, skusim doma a pripadne zatvorim issue, 
jak tak pozeram ten commit, tak ziadna velka zmena... to ma mohlo napadnut ;)

**Comment by Limoto** [comment]
Já jsem to vzal wiresharkem a vypadalo to tam nějak takhle, tak jsem to zkusil a bylo to. Jinak ještě lepší je si přesměrovat odchozí port 1935 na localhost a pustit si rtmpsuck/rtmpsrv (teď nevím který z nich), krásně to vypíše, co posílá originální přehrávač na RTMP. Bohužel Prima má RTMP na portu 80, takže je to dost naprd...

**Comment by j-zelinka** [comment]
Ahoj, zkusil jsem
tv-dl http://play.iprima.cz/all/332161/all -D
a dává to

Arguments:
- movie = None
- quality = None
- get_url = False
- URL = http://play.iprima.cz/all/332161/all
- loglevel = 10
- output = None

Automaticky vybraná kvalita: high
Příkaz: rtmpdump -r "rtmp://bcastew.livebox.cz:80/iprima_token?auth=_any_|1365676426|b51562f5afe873af9e3d214125caabf2643419f9/Prima-1304051527-26852_1000.mp4" -o "Prima-1304051527-26852_1000.flv"  --live
RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: Closing connection: NetStream.Play.StreamNotFound

Zajímavé je, že občas to stáhne půlminutové video s hlášením "Došlo k chybě, zkuste to prosím později."

Jirka
