### ISSUE TITLE
ceskatelevize - specialy

### ISSUE THREAD

**Issue by mehturt** [Limoto/tv-dl#17]
Zdravim, mohli by ste pridat podporu pre stahovanie z ceskatelevize.cz/specialy ?

**Comment by Limoto** [comment]
Zdravím, přesměrovává mě to normálně na pořady. Chápu správně, že chcete stahovat přímo z těch stránek pořadů a neproklikávat se na iVysílání?

**Comment by mehturt** [comment]
Mozno som nieco robil zle, ale chcel som stiahnut video priamo zo stranky, napriklad
http://www.ceskatelevize.cz/specialy/hydepark-civilizace/20.4.2013/
Treba sa niekam preklikavat?
Nastastie ten program co som chcel uz dal niekto na YT, takze uz to nepotrebujem, ale mozno do buducnosti.

**Comment by Limoto** [comment]
Chápu. Podívám se na to.

**Comment by peci1** [comment]
Mne to funguje, kdyz na strance toho specialu v prehravaci kliknu na "Tento porad" v horni liste. Pak to presmeruje na ivysilani a s tim si skript poradi.

**Comment by mehturt** [comment]
@peci1 mate pravdu, cez ivysilani to ide, tuto moznost som predtym nejak nenasiel, diky
