### ISSUE TITLE
prestalo fungovat VOYO

### ISSUE THREAD

**Issue by limotalker** [Limoto/tv-dl#18]
pise to Není k dispozici žádná kvalita videa.
je to jen problem u mne nebo si to nova upravila aby to uz nefungovalo? :-(

prosim pekne, zkuste se na to podivat a opravit to,dekuji za Vasi praci! ;-)

**Comment by limotalker** [comment]
btw na strankach ytd (ceskeho youtube downloaderu) jsem nasel odkaz ze je treba znat TOKEN
nasel sem ho na http://www.tokenmaster.netai.net/ 
token Televize Nova: tajne.heslo
mohu si ten token nejak zmenit ve zdrojaku?

**Comment by limotalker** [comment]
aha tak to je koukam z 23-10-2011 takze asi uz nebude fungovat

**Comment by ghost** [comment]
Ten token skutocne je "tajne.heslo" ale aj tak nefunguje...

**Comment by Limoto** [comment]
Opraveno, viz #19
