### ISSUE TITLE
Stahovani z ivysilani prestalo fungovat

### ISSUE THREAD

**Issue by peci1** [Limoto/tv-dl#20]
Prestalo to fungovat.

Hledal jsem pricinu. V miste, kde vraci odkaz na playlist, zacali ten string URLEnkodovat.

Oprava (otestovano): 
ct.py, radek 72 zmenit na: self.playlist = urlopen(pl_url).read().decode('utf-8').replace('%26', '&')

Pripadne se to asi da opravit "cistsim" zpusobem, nejsem pythonista, takze tohle je takove docasne reseni.

**Comment by Limoto** [comment]
Nespletl sis ten řádek? Mělo by to teď fungovat.

**Comment by peci1** [comment]
Aha, spletl :) Ja jsem si to fixnul u sebe a ten bugreport uz jsem psal jenom z pameti a narychlo =)
