### ISSUE TITLE
Oprava ČT

### ISSUE THREAD

**Issue by Netolish** [Limoto/tv-dl#25]
Dneska jsem chtěl něco stáhnout z ČT a padlo to. Lehkým zkoumáním jsem zjistil,
že ČT vrací adresu playlistu ve formátu
http://cdnls01.nacevi.cz/ls/ClientLink?id=HP92Ky0fpFSvmZk1%26publisher=lsc

tedy v query časti je & nahrazen %26 což je pak pro otevření špatně. V souboru ct.py jsem za řádek 70 doplnil

pl_url = urllib.parse.unquote(pl_url)

Možná to není úplně čisté a chtělo by to unquote jen tu query část URL.

**Comment by Limoto** [comment]
To je zvláštní, vždyť to unquote je na tom řádku 70 a funguje mi to bez problému. Byl problém u nějakýho konkrétního pořadu?

**Comment by Netolish** [comment]
Zlobí mne to u tohoto pořadu:
http://www.ceskatelevize.cz/ivysilani/10525299319-otestujte-svuj-mozek/213382556310001/

Na:
GET /ls/ClientLink?id=HP9pKnYfpFeG9W%26publisher=lsc
vrací "unknown".

Když se %26 nahradí za & tak jak má být už je to v pořádku.

**Comment by Limoto** [comment]
U mě bez problému. Verze Pythonu? tv-dl je aktuální?

**Comment by ghost** [comment]
Chyba byla opravena v commitu e9ec67dae8068a25ac73d8b0f4cdc23bb1ce4122.

**Comment by Netolish** [comment]
Sypu si popel na hlavu. Zapomněl jsem na git pull. Omlouvám se
