### ISSUE TITLE
ct engine problem

### ISSUE THREAD

**Issue by lukasl-cz** [Limoto/tv-dl#30]
Skript vraci chybu pri pokusu stazeni jakehokoli videa z ivysilani. I v pripade pouziti parametru -q list.

Traceback (most recent call last):
  File "./tv-dl", line 123, in <module>
    downloader.main()
  File "./tv-dl", line 29, in main
    e = self.get_engine(self.args.URL)[2](self.args.URL)
  File "/home/test/work/tv-dl/tv-dl-master/engines/ct.py", line 63, in **init**
    data = re.findall(b"callSOAP((.+?));", self.b_page)[0]
IndexError: list index out of range

**Comment by okias** [comment]
Potvrzuji, zkusím se na to podívat, ale zatím tápu.

**Comment by ghost** [comment]
Tady se můžeš klidně inspirovat [ceskatelevize.py](https://github.com/rg3/youtube-dl/blob/master/youtube_dl/extractor/ceskatelevize.py)

**Comment by okias** [comment]
https://github.com/rg3/youtube-dl/issues/2515 není to o moc lepší :P

**Comment by ghost** [comment]
Mě to funguje :)

```
>youtube-dl.exe http://www.ceskatelevize.cz/porady/1186000189-13-komnata/211562210800026-13-komnata-jiriho-hromady
[CeskaTelevize] 211562210800026-13-komnata-jiriho-hromady: Downloading webpage
[CeskaTelevize] 211562210800026-13-komnata-jiriho-hromady: Downloading JSON meta data
[CeskaTelevize] 211562210800026-13-komnata-jiriho-hromady: Downloading XML
[download] Destination: 13. komnata-211562210800026.flv
[download]   0.8% of ~485.30MiB at  1.58MiB/s ETA 04:29
ERROR: Interrupted by user
```

**Comment by Limoto** [comment]
Opraveno (viz #31)
