### ISSUE TITLE
Ukladani do spatneho adresare na Windows

### ISSUE THREAD

**Issue by peci1** [Limoto/tv-dl#33]
Provozuji tv-dl na Windows a ted jsem po cca roce aktualizoval na soucasnou verzi z masteru. Nevim uz, jak presne to fungovalo driv, ale to, co tady popisu, jsem predtim neresil.

Vsiml jsem si, ze na Windows ted neni asi zadna rozumna cesta, jak urcit adresar, do ktereho se ma video ukladat.

Prepinac "-o" mi nepomuze, protoze ve svem spoustecim skriptu nechci z URL parsovat nazev souboru, a kdyz jako output nastavim jenom adresar, tak skript umre na tom, ze nemuze zapsat do "souboru".

Napadlo me tedy spoustet skript z adresare, do ktereho chci stahovat:
ctdown.bat

```
cd /D D:\Download
"C:\Program Files\Python\python.exe" C:\bin\tv-dl-master\tv-dl %*
```

Jenze (napr. pri stahovani z iVysilani) se video neulozi do `D:\Download`, ale do `C:\Program Files (x86)\rtmpdump\nazev_videa` . Takze se nekde pokazi nastaveni aktualniho adresare a uklada se proste tam, odkud bezi rtmpdump.

**Comment by Limoto** [comment]
Omlouvám se za zpoždění, doufám, že to ještě k něčemu bude :-). Přidal jsem možnost přes -o specifikovat pouze adresář.

**Comment by peci1** [comment]
Skvele, ozkouseno. Diky moc.
