### ISSUE TITLE
Barrandov a Prima nefunkční!

### ISSUE THREAD

**Issue by ghost** [Limoto/tv-dl#5]
Windows 7 + Python 3.2.2

<pre>
python tv-dl http://www.iprima.cz/videoarchiv/205049/9416/all -D

Arguments:
 * URL = http://www.iprima.cz/videoarchiv/205049/9416/all
 * get_url = False
 * loglevel = 10
 * movie = None
 * output = None
 * quality = None

Automaticky vybraná kvalita: high
Příkaz: rtmpdump -r "rtmp://bcastnw.livebox.cz:80/iprima_token/Prima-1112121218-13479_1000.mp4" -o "Prima-1112121218-13479_1000.flv"  --live
RTMPDump 2.4 git-6230845 2011-9-25
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
INFO: Connected...
ERROR: rtmp server requested close
</pre>

<pre>
python tv-dl http://www.barrandov.tv/69192-barrandovsvky-videostop-2-epizoda-14 -D

Arguments:
 * URL = http://www.barrandov.tv/69192-barrandovsvky-videostop-2-epizoda-14
 * get_url = False
 * loglevel = 10
 * movie = None
 * output = None
 * quality = None

Příkaz: rtmpdump -r "rtmpe://93.185.103.10/vodpass/mp4:VIDEOSTOP_31_HD.mp4" -o "VIDEOSTOP_31_HD.flv"  --live
RTMPDump 2.4 git-6230845 2011-9-25
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
Connecting ...
WARNING: Trying different position for server digest!
INFO: Connected...
ERROR: RTMP_ReadPacket, failed to read RTMP packet header
</pre>

**Comment by Limoto** [comment]
Opraveno :)

**Comment by ghost** [comment]
Díky.
