### ISSUE TITLE
Voyo a prima

### ISSUE THREAD

**Issue by strublos** [Limoto/tv-dl#9]
VOYO

./tv-dl -o nv 'http://voyo.nova.cz/product/serialy/28058-prvni-krok-epizoda-4-zacatky-jsou-tvrde' -D

Arguments:
- URL = http://voyo.nova.cz/product/serialy/28058-prvni-krok-epizoda-4-zacatky-jsou-tvrde
- get_url = False
- loglevel = 10
- movie = None
- output = nv
- quality = None

Kvality: 
Není k dispozici žádná kvalita videa.

Prima
./tv-dl -o pr 'http://play.iprima.cz/iprima/236013/all' -D

Arguments:
- URL = http://play.iprima.cz/iprima/236013/all
- get_url = False
- loglevel = 10
- movie = None
- output = pr
- quality = None

Traceback (most recent call last):
  File "./tv-dl", line 122, in <module>
    downloader.main()
  File "./tv-dl", line 28, in main
    e = self.get_engine(self.args.URL)[2](self.args.URL)
TypeError: 'NoneType' object is not subscriptable

Díky za opravu

**Comment by Limoto** [comment]
Prima už je, s tou novou si pořád nějak nevím rady, ale snad na to brzo přijdu.

**Comment by strublos** [comment]
Diky za reakci a vubec za vsechno, je to fajn takto moci koukat na videa :)

**Comment by Limoto** [comment]
Voyo opraveno (díky Palimu Rohárovi, kterej poslal patch).
